### PR TITLE
Spatial improvements

### PR DESCRIPTION
**Pull request by tbuckl**
hi @dantonnoriega, i think these changes might be useful to other people. basically, i split up some of the get_routes_sldf, which allowed me to write a modest function called gtfs_routes_df_to_sf_df, based on @mdsumner's comments in issue https://github.com/ropensci/gtfsr/issues/24. while the function is modest, i think it might have broad appeal: writing routes out to GeoJSON or any other GDAL supported driver. 

let me know if you'd prefer to have all these functions tested, or anything else you'd like to see before discussing merging these changes. i totally understand whatever it might be! thanks to all involved for this useful package!

### CODE REVIEW

**Comment by dantonnoriega** [comment]
@tombuckley this is so cool! I'm currently away for vacation but I will take a look when I get back! Been a while since I've made any updates to this package, so this is wonderful.

If you could add some tests for the changes, that would be greatly appreciated. I'll take a look next week!

**Comment by tbuckl** [comment]
thanks @dantonnoriega i'll try to write some tests over the next few days.

**Comment by tbuckl** [comment]
wow sf/travis is more than i bargained for. thankfully @mpadge has a repo for this: https://github.com/mpadge/sftest

but it leaves me wondering: maybe there is a simpler way to do this while abstracting the specific spatial library out of the way. i'll come back to it in the next few days.

**Comment by mdsumner** [comment]
Also this https://github.com/dis-organization/depsf. Sf itself has a more authoritative Travis spec, but ultimately what a project needs can need to be bespoke. Happy to help

**Comment by mpadge** [comment]
It's also possible to do `sf` conversion without `Imports: sf`. It's probably not recommended, but the external `sf` strong dependencies are likely pretty burdensome for many. `osmdata` does full `sf`-compliant extraction with only `Suggests: sf`. Happy to PR extra code if that might help.

**Comment by mdsumner** [comment]
This is tangential, but FWIW  I have two approaches to sf decomposition (without sf) in https://github.com/mdsumner/scsf and https://github.com/mdsumner/spbabel.  I want to not have to worry about these format details, and I'm focussed on approaches to this, generally.  The fragmentation in  this area is unfortunate. 

I will check out the osmdata approach, thanks!

**Comment by tbuckl** [comment]
@mdsumner @mpadge thanks, these are great ideas/pointers.

**Comment by tbuckl** [comment]
@dantonnoriega i'm going to close this PR out for now. can always reopen later. seems to not make sense to have it sitting open without tests passing travis.

**Comment by dantonnoriega** [comment]
I think breaking up the functions is a good idea. 

However, the variables in the original function are incredibly order dependent. Breaking them up into new functions makes it so the variables fail to update (like `shape_ids`). This throws everything off, breaking the routes functions.

I'm going to close this pull request. However, I've pulled a copy of your branch and will incorporate the sf function converters.

Thanks for that contribution!

**Pull request closed without merging**
