### PR TITLE
simplify package to read files only (and submit to cran)

### PR DESCRIPTION
**Pull request by tbuckl**
Dear @eamcvey, 

Thanks for starting this great package. Are you still interested in maintaining it? 

I ask because the lack of response to questions such as https://github.com/ropensci/gtfsr/issues/45 and the open pull request here: https://github.com/ropensci/gtfsr/pull/54 suggest otherwise. 

On the other hand, your employee recently commented in a thread relevant to this pull request [here](https://github.com/ropensci/gtfsr/issues/53), which suggests that you are interested in having your employees maintain the package. 

I hope you'll consider this pull request, which is what your employee proposes for the direction of the package. Note that it also resolves the outstanding CRAN submission question from February. 

Normally, I would not submit such a large pull request, especially given that this other one with a one-line change that simply makes tests pass has gone ignored https://github.com/ropensci/gtfsr/pull/54. 

However, these changes are exactly what your employee proposed here: (https://github.com/ropensci/gtfsr/issues/53).

its important to me that the package continue to work, as we depend on it for projects at work. An example was covered in the news media in the spring:

https://slate.com/business/2018/01/california-bill-sb827-residential-zoning-transit-awesome.html

I totally understand if you'd rather have this package be something that TransLoc's employee's continue to maintain. 

But if you'd like to talk about merging this pull request, I'd be happy to make changes as necessary. Thanks!

### CODE REVIEW

**Comment by dantonnoriega** [comment]
I’m home this weekend and will take a look at this pull request and test it on my local machine.

**Comment by tbuckl** [comment]
thanks @dantonnoriega. these are some pretty massive changes. i totally understand that you may not want to go this direction.

**Comment by dantonnoriega** [comment]
is this pull request necessary given you split off to another package `trread`? when I look at what would be merged, it would drastically change `gtfsr`.

i think i would instead prefer to freeze `gtfsr` in its current state and functionality and help with the split off packages `trread` and `tidytransit`.

thoughts?

**Comment by tbuckl** [comment]
@dantonnoriega whoops you commented here first. sounds great. ill add you as a maintainer on those packages.

**Pull request closed without merging**
