### PR TITLE
clarify names-add examples

### PR DESCRIPTION
**Pull request by tbuckl**
the functions for sf were badly named. this should make them more usable.

### CODE REVIEW

**Comment by tbuckl** [comment]
also added some examples. thanks for the suggestion @mdsumner!

i think this is a bit more legible/usable.

**Comment by tbuckl** [comment]
@mpadge if i've just continued to butcher this i won't take offense if you completely refactor for a cran release.

**Comment by tbuckl** [comment]
ok i merged in @mdsumner's https://github.com/ropensci/gtfsr/pull/46. they are complimentary, i hope.

**Comment by tbuckl** [comment]
this will be more usable if we are clear about whats being converted. as i see it there are just a few possibilities?

1) shapes_to_lines (sfg)
2) routes_to_lines (sf)
3) stops_to_points (sfg)
3) stops_to_points (sf?)

i think it makes sense to call this function `routes_df_as_sf` rather than `convert_gtfs_to_sf` because it only works on the `routes_df`. also happy with any name that helps clarify use. 

it may also be that @mpadge has some great ideas around this related to `dodgr`

**Comment by dantonnoriega** [comment]
These are awesome additions.

I think it’s time to upgrade to a new version!

**Comment by tbuckl** [comment]
@dantonnoriega ok ill take a look at the merge conflict here and reissue. thanks!

**Comment by tbuckl** [comment]
@dantonnoriega should be good to go. totally understand if there's some other reason this PR doesn't work.

**Comment by dantonnoriega** [comment]
awesome! i’ll try to merge again!

**Pull request merged**
